# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.IntegerField()),
                ('image_one', models.ImageField(max_length=254, upload_to='photos')),
                ('image_two', models.ImageField(max_length=254, upload_to='photos')),
            ],
        ),
    ]
