# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='image_id',
            field=models.CharField(max_length=100),
        ),
    ]
